apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: titanic-ml-xthc3-tvv87-kale-marshal-pvc
  namespace: anonymous
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
  volumeMode: Filesystem
